
class Fish {
    constructor (canvas,x,y,height,rotation,rotationsPerSecond,fallPerSecond,creationSource) {
        this.canvas = canvas

        this.x = x
        this.y = y
        this.height = height

        this.rotation = rotation
        this.rotationsPerMs = rotationsPerSecond/1000
        this.fallPerMs = fallPerSecond/1000

        var date = new Date()
        var t = date.getTime()
        this.creationTime = t
        this.lastTickTime = t

        //Fishies make a noise if they're generated by a click, or, 10% of the time, if they're generated by rain.
        if (creationSource == "click" || (creationSource == "rain" && Math.random() > 0.9)) {
            var bingle = new Audio
            bingle.src = "snd/xylophone-"+Math.ceil(Math.random()*8)+".mp3"
            bingle.play()
        }
    }
    
    //--------------------Motion--------------------
    tick() {
        var date = new Date()
        var t = date.getTime()
        this.rotation = (this.rotation+this.rotationsPerMs*(t-this.lastTickTime))%1
        this.y += this.fallPerMs*(t-this.lastTickTime)
        this.lastTickTime = t
    }

    //--------------------Drawing--------------------
    draw() {
        this.canvas.beginPath()
        this.canvas.strokeStyle = "#fa0" //Fishies are ALWAYS orange.

        //Drawing the fish.
        for (var i = 0; i < this.height*10; i++) {
            var y = this.height*-3*Math.cos((2*i/Math.PI)/this.height)/2
            var x = this.height*Math.cos((3*i/Math.PI)/this.height)/2
            var rotX = x*Math.cos(this.rotation*2*Math.PI)-y*Math.sin(this.rotation*2*Math.PI)
            var rotY= x*Math.sin(this.rotation*2*Math.PI)+y*Math.cos(this.rotation*2*Math.PI)
            this.canvas.lineTo(rotX+this.x,rotY+this.y)
        }

        //If the fish was created in the last 200 milliseconds, drawing "sparkles"
        var date = new Date()
        var t = date.getTime()
        if (t-this.creationTime < 200) {
            var sparkleLength = 10
            var sparkles = 12
            for (var r = 0; r < sparkles; r++) {
                this.canvas.moveTo(this.x+2*this.height*Math.sin(r/sparkles*2*Math.PI),this.y+2*this.height*Math.cos(r/sparkles*2*Math.PI))
                this.canvas.lineTo(this.x+(this.height+sparkleLength)*Math.sin(r/sparkles*2*Math.PI),this.y+(this.height+sparkleLength)*Math.cos(r/sparkles*2*Math.PI))
            }
        }

        this.canvas.stroke()
    }
}